### ISSUE TITLE
Panic when using proper English intepunction

### ISSUE THREAD

**Issue by matmilbury** [alexfertel/bulloak#52] opened 2024-01-18 13:38 UTC
Given an example:

```tree
Foo
└── It can’t do X.
```

`bulloak scaffold` panics.

Notice, `’` is used instead of `'`.

**Comment by alexfertel** [comment] 2024-01-18 14:30
Published 🎉 !

Lmk if you find any issues. Closing this now.

**Closed by alexfertel** 2024-01-18 14:30 UTC
Labels: Bug

**Comment by matmilbury** [comment] 2024-01-18 14:38
wow thank you @alexfertel, I’m impressed with how well you maintain bulloak

**Comment by matmilbury** [comment] 2024-01-18 14:44
I just looked at the fix implementation.

If I understand correctly, currently the bulloak uses a blacklist approach, replacing all characters that should not appear in the function name.

Have you thought about using a whitelist approach instead? Stripping all characters except allowed? For solidity function name that would be something along the lines of [a-zA-Z0-9_-]

**Comment by alexfertel** [comment] 2024-01-18 14:54
> I’m impressed with how well you maintain bulloak

Thank you! ❤️ 

> Have you thought about using a whitelist approach instead? 

Yes, the problem is that the change is a bit more involved because I'm not sanitizing exactly where I need to, so for example, `[a-zA-Z0-9_-]` would strip spaces, which breaks a few things.

I need to make some time and refactor this into a proper solution. Thanks for the suggestion, and actually, if you want to do a follow-up PR, let me know.

**Comment by matmilbury** [comment] 2024-01-18 14:57
Yeah, I agree that approach will require more resources. I see an opportunity for nice fuzzy tests with this.
